### ISSUE TITLE
Game crash due to changing specific content to Erekir

### ISSUE THREAD

**Issue by K6ZXS** [liplum/CyberIO#40]
Mindustry has crashed. How unfortunate.
Version: release build 144.3
OS: Windows 10 x64 (amd64)
Java Version: 16.0.1
Runtime Available Memory: 2022mb
Cores: 4
Mods: cyber-io:5.1-erekir

arc.util.ArcRuntimeException: java.lang.NullPointerException: Cannot read field "name" because "region" is null
	at arc.assets.AssetManager.handleTaskError(AssetManager.java:669)
	at arc.assets.AssetManager.update(AssetManager.java:441)
	at arc.assets.AssetManager.update(AssetManager.java:464)
	at mindustry.ClientLauncher.update(ClientLauncher.java:206)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:204)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:192)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:54)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:39)
Caused by: java.lang.NullPointerException: Cannot read field "name" because "region" is null
	at mindustry.mod.Mods$1.getPixmap(Mods.java:332)
	at arc.graphics.g2d.TextureAtlas.getPixmap(TextureAtlas.java:144)
	at mindustry.world.Block.createIcons(Block.java:1330)
	at mindustry.mod.Mods.lambda$loadSync$11(Mods.java:350)
	at arc.struct.Seq.each(Seq.java:189)
	at mindustry.mod.Mods.loadSync(Mods.java:344)
	at arc.assets.AssetManager$2.loadSync(AssetManager.java:357)
	at arc.assets.AssetLoadingTask.handleAsyncLoader(AssetLoadingTask.java:108)
	at arc.assets.AssetLoadingTask.update(AssetLoadingTask.java:73)
	at arc.assets.AssetManager.updateTask(AssetManager.java:590)
	at arc.assets.AssetManager.update(AssetManager.java:439)
	... 6 more

**Comment by liplum** [comment]
It's due to the API changes between 144 and the version that Cyber IO 5.1 on (about 141).
I would fix it soon.

**Comment by Xcaliburr101** [comment]
i have the same issue, should i disable the mod for now or is there an easy fix? filling a name in the region does not sound difficult, but communicating trough an API does.
`
```
Mindustry has crashed. How unfortunate.
Version: steam build 145.1
OS: Windows 10 x64 (amd64)
Java Version: 16.0.1
Runtime Available Memory: 3936mb
Cores: 12
Mods: cyber-io:5.1-erekir

arc.util.ArcRuntimeException: java.lang.NullPointerException: Cannot read field "name" because "region" is null
	at arc.assets.AssetManager.handleTaskError(AssetManager.java:669)
	at arc.assets.AssetManager.update(AssetManager.java:441)
	at arc.assets.AssetManager.update(AssetManager.java:464)
	at mindustry.ClientLauncher.update(ClientLauncher.java:206)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:204)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:192)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:54)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:39)
Caused by: java.lang.NullPointerException: Cannot read field "name" because "region" is null
	at mindustry.mod.Mods$1.getPixmap(Mods.java:334)
	at arc.graphics.g2d.TextureAtlas.getPixmap(TextureAtlas.java:144)
	at mindustry.world.Block.createIcons(Block.java:1337)
	at mindustry.mod.Mods.lambda$loadSync$11(Mods.java:352)
	at arc.struct.Seq.each(Seq.java:189)
	at mindustry.mod.Mods.loadSync(Mods.java:346)
	at arc.assets.AssetManager$2.loadSync(AssetManager.java:357)
	at arc.assets.AssetLoadingTask.handleAsyncLoader(AssetLoadingTask.java:108)
	at arc.assets.AssetLoadingTask.update(AssetLoadingTask.java:73)
	at arc.assets.AssetManager.updateTask(AssetManager.java:590)
	at arc.assets.AssetManager.update(AssetManager.java:439)
	... 6 more
`
```
