### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by Mac33299** [liplum/CyberIO#42]
Mindustry has crashed. How unfortunate.
Version: release build 145.1
OS: Windows 10 x64 (amd64)
Java Version: 1.8.0_371
Runtime Available Memory: 1796mb
Cores: 8
Mods: cyber-io:5.1-erekir

arc.util.ArcRuntimeException: java.lang.NullPointerException
	at arc.assets.AssetManager.handleTaskError(AssetManager.java:669)
	at arc.assets.AssetManager.update(AssetManager.java:441)
	at arc.assets.AssetManager.update(AssetManager.java:464)
	at mindustry.ClientLauncher.update(ClientLauncher.java:206)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:204)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:192)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:54)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:39)
Caused by: java.lang.NullPointerException
	at mindustry.mod.Mods$1.getPixmap(Mods.java:334)
	at arc.graphics.g2d.TextureAtlas.getPixmap(TextureAtlas.java:144)
	at mindustry.world.Block.createIcons(Block.java:1337)
	at mindustry.mod.Mods.lambda$loadSync$11(Mods.java:352)
	at arc.struct.Seq.each(Seq.java:189)
	at mindustry.mod.Mods.loadSync(Mods.java:346)
	at arc.assets.AssetManager$2.loadSync(AssetManager.java:357)
	at arc.assets.AssetLoadingTask.handleAsyncLoader(AssetLoadingTask.java:108)
	at arc.assets.AssetLoadingTask.update(AssetLoadingTask.java:73)
	at arc.assets.AssetManager.updateTask(AssetManager.java:590)
	at arc.assets.AssetManager.update(AssetManager.java:439)
	... 6 more

**Comment by THE-EXP** [comment]
```
Mindustry has crashed. How unfortunate.
Version: steam build 146
OS: Windows 10 x64 (amd64)
Java Version: 16.0.1
Runtime Available Memory: 8148mb
Cores: 24
Mods: cyber-io:5.1-erekir
arc.util.ArcRuntimeException: java.lang.NullPointerException: Cannot read field "name" because "region" is null
	at arc.assets.AssetManager.handleTaskError(AssetManager.java:669)
	at arc.assets.AssetManager.update(AssetManager.java:441)
	at arc.assets.AssetManager.update(AssetManager.java:464)
	at mindustry.ClientLauncher.update(ClientLauncher.java:215)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:204)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:192)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:54)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:39)
Caused by: java.lang.NullPointerException: Cannot read field "name" because "region" is null
	at mindustry.mod.Mods$1.getPixmap(Mods.java:335)
	at arc.graphics.g2d.TextureAtlas.getPixmap(TextureAtlas.java:144)
	at mindustry.world.Block.createIcons(Block.java:1344)
	at mindustry.mod.Mods.lambda$loadSync$11(Mods.java:353)
	at arc.struct.Seq.each(Seq.java:189)
	at mindustry.mod.Mods.loadSync(Mods.java:347)
	at arc.assets.AssetManager$2.loadSync(AssetManager.java:357)
	at arc.assets.AssetLoadingTask.handleAsyncLoader(AssetLoadingTask.java:108)
	at arc.assets.AssetLoadingTask.update(AssetLoadingTask.java:73)
	at arc.assets.AssetManager.updateTask(AssetManager.java:590)
	at arc.assets.AssetManager.update(AssetManager.java:439)
	... 6 more
```
Happens when switching to erekir content

**Comment by JojoFR1** [comment]
It's a know bug and will be fixed soon™

**Comment by NiXTheDev** [comment]
Ah yes, the soon™ time

**Comment by JojoFR1** [comment]
The upcoming week probably. Liplum is making his great comeback

**Comment by NiXTheDev** [comment]
Oh, seems I decided to get myself a PC version at a right time, I quite like this mod, brings good old memories about the Mindustry when it still was what is now "Mindustry: classic", conveyor teleporters, though, they are a bit op without consuming any power, CyberIO makes it at least fair

**Comment by liplum** [comment]
Fixed in Cyber IO v6.0

**Comment by NiXTheDev** [comment]
now we only need to wait for the build of v6 and we're truly done

also don't forget #40 and #41

**Comment by liplum** [comment]
> now we only need to wait for the build of v6 and we're truly done

There are still some bug should to be fixed in v6.

**Comment by NiXTheDev** [comment]
Understood 👍
