### ISSUE TITLE
mindustry crash

### ISSUE THREAD

**Issue by 123d255** [liplum/CyberIO#46]
[I] [GL] Version: OpenGL 4.6.0 / NVIDIA Corporation / NVIDIA GeForce RTX 4070/PCIe/SSE2
[I] [GL] Max texture size: 32768
[I] [GL] Using OpenGL 2 context.
[I] [JAVA] Version: 1.8.0_411
[I] [RAM] Available: 6.9 GB
[I] [Mindustry] Version: 146
[I] [CyberIO]v5.1 loading started.
[I] [CyberIO]Update checking...
[I] [CyberIO][Java Info]
java.vm.name: Java HotSpot(TM) 64-Bit Server VM
java.vm.vendor: Oracle Corporation
java.vm.specification.version: 1.8
java.vm.version: 25.411-b09
java.version: 1.8.0_411
java.class.version: 52.0
[I] //===Cyber IO Compatible===\\
[I] [CyberIO]TvStatic|false
[I] \\=========================//
[I] Loaded mod 'cyber-io' in 73.857ms
[I] [CyberIO]The latest version is 5.1
[I] [CyberIO]v5.1 erekir mod's contents loaded.
[E] arc.util.ArcRuntimeException: java.lang.NullPointerException
	at arc.assets.AssetManager.handleTaskError(AssetManager.java:669)
	at arc.assets.AssetManager.update(AssetManager.java:441)
	at arc.assets.AssetManager.update(AssetManager.java:464)
	at mindustry.ClientLauncher.update(ClientLauncher.java:215)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:204)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:192)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:54)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:39)
Caused by: java.lang.NullPointerException
	at mindustry.mod.Mods$1.getPixmap(Mods.java:335)
	at arc.graphics.g2d.TextureAtlas.getPixmap(TextureAtlas.java:144)
	at mindustry.world.Block.createIcons(Block.java:1344)
	at mindustry.mod.Mods.lambda$loadSync$11(Mods.java:353)
	at arc.struct.Seq.each(Seq.java:189)
	at mindustry.mod.Mods.loadSync(Mods.java:347)
	at arc.assets.AssetManager$2.loadSync(AssetManager.java:357)
	at arc.assets.AssetLoadingTask.handleAsyncLoader(AssetLoadingTask.java:108)
	at arc.assets.AssetLoadingTask.update(AssetLoadingTask.java:73)
	at arc.assets.AssetManager.updateTask(AssetManager.java:590)
	at arc.assets.AssetManager.update(AssetManager.java:439)
	... 6 more

**Comment by JojoFR1** [comment]
It's a know issue and it'll be fixed in next update (whenever that'll come out)
